language: php

php:
  - 7.4

services:
  - mysql
  - memcached
  - redis-server
  - rabbitmq
  - nginx

addons:
  apt:
    packages:
    - rabbitmq-server

sudo: false

env:
  global:
      - DATA_API_MYSQL_HOST: "127.0.0.1"
      - DATA_API_MYSQL_PASS: ""
      - DATA_API_MYSQL_USER: "root"
      - DATA_API_MYSQL_NAME: "baka"
      - DATA_API_MEMCACHED_HOST: "127.0.0.1"
      - DATA_API_MEMCACHED_PORT: 11211
      - DATA_API_MEMCACHED_WEIGHT: 100
      - REDIS_HOST: "127.0.0.1"
      - REDIS_PORT: 6379
      - APP_IP: "api.baka.ld"
      - APP_ENV: development
      - PHINX_CONFIG_DIR: "/home/scrutinizer/build/storage"

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - ~/cphalcon
  
install:
  - composer self-update
  - composer clearcache
  - cd ~/ && rm -rf cphalcon && git clone -b 4.0.x -q --depth=1 https://github.com/phalcon/cphalcon.git && cd cphalcon/build && ./install
  - cd ~/ && git clone https://github.com/jbboehr/php-psr.git && cd php-psr && phpize && ./configure  && make && make test && make install
  - echo 'extension = "psr.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'extension = "phalcon.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - php --ri phalcon
  - wget https://github.com/swoole/swoole-src/archive/v4.4.x.tar.gz -O swoole.tar.gz && mkdir -p swoole && tar -xf swoole.tar.gz -C swoole --strip-components=1 && rm swoole.tar.gz && cd swoole && phpize && ./configure && make -j$(nproc) && make install && cd - && rm -rf swoole
  - echo "extension = swoole.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  
before_script:
  - cd $TRAVIS_BUILD_DIR
  - cp storage/ci/.env.example .env
  - cp storage/ci/phinx.php.example phinx.php
  - mysql -e "CREATE DATABASE baka"
  - sudo redis-server /etc/redis/redis.conf --port 6379
  - composer install --no-interaction
  - composer update --no-interaction
  - ./vendor/bin/phinx migrate -e development
  - ./vendor/bin/phinx seed:run
  - php cli/cli.php setup
  - php cli/cli.php acl crm
  - sudo rabbitmqctl status

script:
  - ./vendor/bin/codecept run
